title: Zato Development
email: maks.mishinFZ@gmail.com
author: Макс Мишин
description: >-
  Блог о разработке и преподавании.
baseurl: ""
url: ""
github_username:  maks-mishin
linkedin_username: maks-mishin-a1450717a
telegram_username: maks_mishin

# Build settings
theme: minima
plugins:
  - jekyll-feed

